language: python
python:
  - "2.6"
  - "2.7"
# test against different versions of Django
env:
  - DJANGO_VERSION=">=1.3,<1.4"
  - DJANGO_VERSION=">=1.4,<1.5"
# command to install dependencies
install: pip install --use-mirrors . -r requirements-test.txt Django$DJANGO_VERSION
# command to run tests
script:
  - coverage run --source=survey django-admin.py test --settings=survey.test_settings survey
  - coveralls
