language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

# test against different versions of Django
env:
  - DJANGO_VERSION=">=1.3,<1.4"
  - DJANGO_VERSION=">=1.4,<1.5"
  - DJANGO_VERSION=">=1.5,<1.6"

# command to install dependencies
install: pip install . -r requirements-test.txt Django$DJANGO_VERSION

# command to run tests
script:
  - coverage run --source=survey -m django.bin.django-admin test --settings=survey.test_settings --noinput survey

after_success:
  - pip install -q coveralls
  - coveralls

matrix:
  # exclude incompatible combinations of python+django
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=">=1.3,<1.4"
    - python: "3.3"
      env: DJANGO_VERSION=">=1.4,<1.5"
  # experimental builds
  allow_failures:
    - python: "3.3"
    - python: "pypy"

notifications:
  email: false

env:
  - PIP_USE_MIRRORS=true
